### ISSUE TITLE
Challening method naming

### ISSUE THREAD

**Issue by AlexKap23** [Atia1978/Tic_Tac_Toe_Games#1]
https://github.com/Atia1978/Tic_Tac_Toe_Games/blob/f8ffbc4ab9957b9bd5876915f852400c493a98bd/Tic_Tac_Toe_Games/GameCodes.cs#L30

This method is not choosing player's symbol but it's more like assigning a symbol to the player. The symbol has been already provided by the user on ChooseSymbol method. So this method **ChosePlayerSymbols** should have a different name.

**Comment by Atia1978** [comment]
When checking out this commit it will rename ChosePlayerSymbols to AssignPlayerSymbols for better clarity.
