### ISSUE TITLE
Prefer local variables over static

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/Tic_Tac_Toe_Games#3]
https://github.com/Atia1978/Tic_Tac_Toe_Games/blob/367abf099e320c8fb25b663c3514a8512662650b/Tic_Tac_Toe_Games/Program.cs#L7-L9

Those variables do not need to be private fields: you only make use of them from within your Program Main funtion so at least `playSymbol` and `grid`could be defined inside your main function.
The const for `GRID_SIZE` is already defined in your "GameElements" class so you could use that :D

**Comment by Atia1978** [comment]
When checking out this commit it will move playSymbol and grid inside Main function and use GameConstants.GRID_SIZE for consistency.
