### ISSUE TITLE
Class name seems missleading

### ISSUE THREAD

**Issue by AlexKap23** [Atia1978/Tic_Tac_Toe_Games#4]
https://github.com/Atia1978/Tic_Tac_Toe_Games/blob/40f833dd791cffc533d5c2b0236db99d69cc6b77/Tic_Tac_Toe_Games/GameElement.cs#L9C20-L9C31

why do you call this class GameElement? It only contains constants. Usually classes that contain constants contain the word Constants in their name. For example on a system that has multiple constant files but for different domains, for example constants for orders and users, you create the classes with name OrderConstants and UserConstants. But if there's only one constant file, you can simply call it Constants. 

GameElement seems kind of missleading. What is the idea behind that?

**Comment by Atia1978** [comment]
When checking out this commit it will rename GameElement to GameConstants for better clarity and consistency in naming.
