### ISSUE TITLE
Why don't you check the invalid first?

### ISSUE THREAD

**Issue by AlexKap23** [Atia1978/Tic_Tac_Toe_Games#5]
https://github.com/Atia1978/Tic_Tac_Toe_Games/blob/40f833dd791cffc533d5c2b0236db99d69cc6b77/Tic_Tac_Toe_Games/GameCodes.cs#L41

instead of checking availableCells.Count>0 which is the valid case for you, you can start with the opposite first and immediatelty return false since the available cells are less than 0 or even 0. 

by this approach the complexity of the code will be lower since the if case will just contain a return instead of your while loop. it will also make the code much easier to read since you are ruling out the invalid cases first.

**Comment by Atia1978** [comment]
When checking out this commit it,will refactor PlaceAIMove by returning early when no available cells exist, improving readability and efficiency.
