### ISSUE TITLE
avoid leaving empty lines on your code

### ISSUE THREAD

**Issue by AlexKap23** [Atia1978/Tic_Tac_Toe_Games#6]
https://github.com/Atia1978/Tic_Tac_Toe_Games/blob/40f833dd791cffc533d5c2b0236db99d69cc6b77/Tic_Tac_Toe_Games/GameCodes.cs#L122-L123

those lines have no efect and they make the method extend further in the file. avoid having empty lines in general. check your code for more situation like this

**Comment by Atia1978** [comment]
When checking out this commit it will remove unnecessary empty lines and improve code readability.
